channels:
  - conda-forge
dependencies:
  - python=3.7
  - invoke=1.5.0
  - attrs=20.3.0
  - toolz=0.11.1
  - bidict=0.21.2
  - networkx=2.5
  - cloudpickle=1.6.0
  - protobuf=3.11
  - grpcio=1.23
  - grpcio-tools=1.16
  - pymongo=3.11.0
  - numpy=1.19.5
  - pandas=1.2.0
  - pytorch=1.7.1
  - cudatoolkit=11.0.221
  - pytest=6.2.1
  - pytest-cov=2.10.1
  - hypothesis=6.0.0
  - pip=21.2
  - pip:
      - pulsar-client==2.7.0