version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew --no-daemon :gradient-service-domain:build

reports:
  test-gradient-service-domain:
    files:
      - "*.xml"
    base-directory: "gradient-service-domain/build/reports/tests/test"
    file-format: JUNITXML
cache:
  paths:
    - "/root/.m2/**/*"