version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      pip install pytest
  build:
    on-failure: ABORT
    commands:
      pytest tests
