version: 0.2

phases:
  build:
    commands:
      - ./gradlew build

reports:
  test-gradient-sensor:
    files:
      - "*.xml"
    base-directory: "gradient-sensor/build/test-results/test/"
    file-format: JUNITXML
  test-gradient-service-code:
    files:
      - "*.xml"
    base-directory: "gradient-service-code/build/test-results/test/"
    file-format: JUNITXML
  test-gradient-service-monitoring:
    files:
      - "*.xml"
    base-directory: "gradient-service-monitoring/build/test-results/test/"
    file-format: JUNITXML
cache:
  paths:
    - "/root/.m2/**/*"