/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.8.2/userguide/multi_project_builds.html
 */

rootProject.name = "gradient-service"
include(
    "gradient-service-api",
    "gradient-service-api:code",
    "gradient-service-api:dataset",
    "gradient-service-api:event",
    "gradient-service-api:model",
    "gradient-service-api:project",
    "gradient-service-code",
    "gradient-service-project",
    "gradient-service-dataset",
    "gradient-service-monitoring",
    "gradient-service-model",
)
