# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_entity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from gradient.model.api import common_entity_pb2 as common__entity__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_entity.proto',
  package='org.sourceflow.gradient.model',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12model_entity.proto\x12\x1dorg.sourceflow.gradient.model\x1a\x13\x63ommon_entity.proto\"K\n\x11ModelHandleDetail\x12\x36\n\x08model_id\x18\x01 \x01(\x0b\x32$.org.sourceflow.gradient.common.UUID\"\xb3\x01\n\x0cModelMessage\x12G\n\x0fproject_context\x18\x01 \x01(\x0b\x32..org.sourceflow.gradient.common.ProjectContext\x12O\n\x13model_handle_detail\x18\x02 \x01(\x0b\x32\x30.org.sourceflow.gradient.model.ModelHandleDetailH\x00\x42\t\n\x07payloadb\x06proto3')
  ,
  dependencies=[common__entity__pb2.DESCRIPTOR,])




_MODELHANDLEDETAIL = _descriptor.Descriptor(
  name='ModelHandleDetail',
  full_name='org.sourceflow.gradient.model.ModelHandleDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='org.sourceflow.gradient.model.ModelHandleDetail.model_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=149,
)


_MODELMESSAGE = _descriptor.Descriptor(
  name='ModelMessage',
  full_name='org.sourceflow.gradient.model.ModelMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_context', full_name='org.sourceflow.gradient.model.ModelMessage.project_context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_handle_detail', full_name='org.sourceflow.gradient.model.ModelMessage.model_handle_detail', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='org.sourceflow.gradient.model.ModelMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=152,
  serialized_end=331,
)

_MODELHANDLEDETAIL.fields_by_name['model_id'].message_type = common__entity__pb2._UUID
_MODELMESSAGE.fields_by_name['project_context'].message_type = common__entity__pb2._PROJECTCONTEXT
_MODELMESSAGE.fields_by_name['model_handle_detail'].message_type = _MODELHANDLEDETAIL
_MODELMESSAGE.oneofs_by_name['payload'].fields.append(
  _MODELMESSAGE.fields_by_name['model_handle_detail'])
_MODELMESSAGE.fields_by_name['model_handle_detail'].containing_oneof = _MODELMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['ModelHandleDetail'] = _MODELHANDLEDETAIL
DESCRIPTOR.message_types_by_name['ModelMessage'] = _MODELMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelHandleDetail = _reflection.GeneratedProtocolMessageType('ModelHandleDetail', (_message.Message,), dict(
  DESCRIPTOR = _MODELHANDLEDETAIL,
  __module__ = 'model_entity_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.model.ModelHandleDetail)
  ))
_sym_db.RegisterMessage(ModelHandleDetail)

ModelMessage = _reflection.GeneratedProtocolMessageType('ModelMessage', (_message.Message,), dict(
  DESCRIPTOR = _MODELMESSAGE,
  __module__ = 'model_entity_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.model.ModelMessage)
  ))
_sym_db.RegisterMessage(ModelMessage)


# @@protoc_insertion_point(module_scope)