# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gradient.model.api import model_entity_pb2 as model__entity__pb2


class ModelServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadModel = channel.unary_unary(
        '/org.sourceflow.gradient.model.ModelService/LoadModel',
        request_serializer=model__entity__pb2.ModelMessage.SerializeToString,
        response_deserializer=model__entity__pb2.ModelMessage.FromString,
        )


class ModelServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoadModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadModel': grpc.unary_unary_rpc_method_handler(
          servicer.LoadModel,
          request_deserializer=model__entity__pb2.ModelMessage.FromString,
          response_serializer=model__entity__pb2.ModelMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'org.sourceflow.gradient.model.ModelService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))