name: gradient-service-api
channels:
  - conda-forge
dependencies:
  - python=3.7
  - invoke=1.5.0
  - pip=21.2
  - attrs=21.2.0
  - boto3=1.18.26
  - grpcio-tools=1.33.2
  - twine=3.4.2 # dev
  - conda-build=3.21.4 # dev