# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ..entities import project_pb2 as org_dot_sourceflow_dot_gradient_dot_entities_dot_project__pb2


class ProjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterProject = channel.unary_unary(
                '/org.sourceflow.gradient.services.ProjectService/RegisterProject',
                request_serializer=org_dot_sourceflow_dot_gradient_dot_entities_dot_project__pb2.ProjectMessage.SerializeToString,
                response_deserializer=org_dot_sourceflow_dot_gradient_dot_entities_dot_project__pb2.ProjectMessage.FromString,
                )


class ProjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterProject': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProject,
                    request_deserializer=org_dot_sourceflow_dot_gradient_dot_entities_dot_project__pb2.ProjectMessage.FromString,
                    response_serializer=org_dot_sourceflow_dot_gradient_dot_entities_dot_project__pb2.ProjectMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.sourceflow.gradient.services.ProjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.sourceflow.gradient.services.ProjectService/RegisterProject',
            org_dot_sourceflow_dot_gradient_dot_entities_dot_project__pb2.ProjectMessage.SerializeToString,
            org_dot_sourceflow_dot_gradient_dot_entities_dot_project__pb2.ProjectMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)