version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh -q
      - bash miniconda.sh -b -p $HOME/miniconda
      - source $HOME/miniconda/etc/profile.d/conda.sh
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a
      - conda env create -f requirements.yaml

  pre_build:
    commands:
      - conda run --live-stream -n gradient-service-model inv install

  build:
    commands:
      - conda run --live-stream -n gradient-service-model inv build

  post_build:
    commands:
      - conda run --live-stream -n gradient-service-model inv test

reports:
  test-gradient-service-model:
    files:
      - "*.xml"
    base-directory: "build/pytest/reports"
    file-format: JUNITXML
cache:
  paths:
    - "/root/.cache/pip/**/*"
