# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/sourceflow/gradient/entities/inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='org/sourceflow/gradient/entities/inference.proto',
  package='org.sourceflow.gradient.entities',
  syntax='proto3',
  serialized_options=b'\n*org.sourceflow.gradient.inference.entitiesB\021InferenceEntities',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0org/sourceflow/gradient/entities/inference.proto\x12 org.sourceflow.gradient.entities\x1a-org/sourceflow/gradient/entities/common.proto\"M\n\x11ModelHandleDetail\x12\x38\n\x08model_id\x18\x01 \x01(\x0b\x32&.org.sourceflow.gradient.entities.UUID\"\xb8\x01\n\x0cModelMessage\x12I\n\x0fproject_context\x18\x01 \x01(\x0b\x32\x30.org.sourceflow.gradient.entities.ProjectContext\x12R\n\x13model_handle_detail\x18\x02 \x01(\x0b\x32\x33.org.sourceflow.gradient.entities.ModelHandleDetailH\x00\x42\t\n\x07payloadB?\n*org.sourceflow.gradient.inference.entitiesB\x11InferenceEntitiesb\x06proto3'
  ,
  dependencies=[org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2.DESCRIPTOR,])




_MODELHANDLEDETAIL = _descriptor.Descriptor(
  name='ModelHandleDetail',
  full_name='org.sourceflow.gradient.entities.ModelHandleDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='org.sourceflow.gradient.entities.ModelHandleDetail.model_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=210,
)


_MODELMESSAGE = _descriptor.Descriptor(
  name='ModelMessage',
  full_name='org.sourceflow.gradient.entities.ModelMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_context', full_name='org.sourceflow.gradient.entities.ModelMessage.project_context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_handle_detail', full_name='org.sourceflow.gradient.entities.ModelMessage.model_handle_detail', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='org.sourceflow.gradient.entities.ModelMessage.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=213,
  serialized_end=397,
)

_MODELHANDLEDETAIL.fields_by_name['model_id'].message_type = org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2._UUID
_MODELMESSAGE.fields_by_name['project_context'].message_type = org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2._PROJECTCONTEXT
_MODELMESSAGE.fields_by_name['model_handle_detail'].message_type = _MODELHANDLEDETAIL
_MODELMESSAGE.oneofs_by_name['payload'].fields.append(
  _MODELMESSAGE.fields_by_name['model_handle_detail'])
_MODELMESSAGE.fields_by_name['model_handle_detail'].containing_oneof = _MODELMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['ModelHandleDetail'] = _MODELHANDLEDETAIL
DESCRIPTOR.message_types_by_name['ModelMessage'] = _MODELMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelHandleDetail = _reflection.GeneratedProtocolMessageType('ModelHandleDetail', (_message.Message,), {
  'DESCRIPTOR' : _MODELHANDLEDETAIL,
  '__module__' : 'org.sourceflow.gradient.entities.inference_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.ModelHandleDetail)
  })
_sym_db.RegisterMessage(ModelHandleDetail)

ModelMessage = _reflection.GeneratedProtocolMessageType('ModelMessage', (_message.Message,), {
  'DESCRIPTOR' : _MODELMESSAGE,
  '__module__' : 'org.sourceflow.gradient.entities.inference_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.ModelMessage)
  })
_sym_db.RegisterMessage(ModelMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)