# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/sourceflow/gradient/entities/introspect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='org/sourceflow/gradient/entities/introspect.proto',
  package='org.sourceflow.gradient.entities',
  syntax='proto3',
  serialized_options=b'\n+org.sourceflow.gradient.introspect.entitiesB\022IntrospectEntities',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1org/sourceflow/gradient/entities/introspect.proto\x12 org.sourceflow.gradient.entities\"M\n\x11IntrospectMessage\x12\x38\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32(.org.sourceflow.gradient.entities.Action*\x13\n\x06\x41\x63tion\x12\t\n\x05RESET\x10\x00\x42\x41\n+org.sourceflow.gradient.introspect.entitiesB\x12IntrospectEntitiesb\x06proto3'
)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='org.sourceflow.gradient.entities.Action',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=166,
  serialized_end=185,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
RESET = 0



_INTROSPECTMESSAGE = _descriptor.Descriptor(
  name='IntrospectMessage',
  full_name='org.sourceflow.gradient.entities.IntrospectMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='org.sourceflow.gradient.entities.IntrospectMessage.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=164,
)

_INTROSPECTMESSAGE.fields_by_name['action'].enum_type = _ACTION
DESCRIPTOR.message_types_by_name['IntrospectMessage'] = _INTROSPECTMESSAGE
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntrospectMessage = _reflection.GeneratedProtocolMessageType('IntrospectMessage', (_message.Message,), {
  'DESCRIPTOR' : _INTROSPECTMESSAGE,
  '__module__' : 'org.sourceflow.gradient.entities.introspect_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.IntrospectMessage)
  })
_sym_db.RegisterMessage(IntrospectMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)