# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/sourceflow/gradient/entities/monitoring.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='org/sourceflow/gradient/entities/monitoring.proto',
  package='org.sourceflow.gradient.entities',
  syntax='proto3',
  serialized_options=b'\n+org.sourceflow.gradient.monitoring.entitiesB\022MonitoringEntities',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1org/sourceflow/gradient/entities/monitoring.proto\x12 org.sourceflow.gradient.entities\x1a-org/sourceflow/gradient/entities/common.proto\"\xbf\x01\n\x0fMonitoringEvent\x12\x43\n\x04type\x18\x01 \x01(\x0e\x32\x35.org.sourceflow.gradient.entities.MonitoringEventType\x12\x0f\n\x07\x66rameId\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\x05\x12\x0e\n\x06target\x18\x04 \x01(\x05\x12\x36\n\x05\x64\x61tum\x18\x05 \x01(\x0b\x32\'.org.sourceflow.gradient.entities.Datum\"\xc6\x01\n\x05\x46rame\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1d\n\x15\x66rame_code_element_id\x18\x03 \x01(\x05\x12\x41\n\x06\x65vents\x18\x04 \x03(\x0b\x32\x31.org.sourceflow.gradient.entities.MonitoringEvent\x12O\n\x14related_child_events\x18\x05 \x03(\x0b\x32\x31.org.sourceflow.gradient.entities.MonitoringEvent\"\x9d\x01\n\x16MonitoringStreamDetail\x12@\n\x07\x63ontrol\x18\x01 \x01(\x0b\x32/.org.sourceflow.gradient.entities.StreamControl\x12\x41\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x31.org.sourceflow.gradient.entities.MonitoringEvent\"\x8e\x01\n\x11\x46rameStreamDetail\x12@\n\x07\x63ontrol\x18\x01 \x01(\x0b\x32/.org.sourceflow.gradient.entities.StreamControl\x12\x37\n\x06\x66rames\x18\x02 \x03(\x0b\x32\'.org.sourceflow.gradient.entities.Frame\"\x9b\x02\n\x11MonitoringMessage\x12I\n\x0fproject_context\x18\x01 \x01(\x0b\x32\x30.org.sourceflow.gradient.entities.ProjectContext\x12\\\n\x18monitoring_stream_detail\x18\x02 \x01(\x0b\x32\x38.org.sourceflow.gradient.entities.MonitoringStreamDetailH\x00\x12R\n\x13\x66rame_stream_detail\x18\x03 \x01(\x0b\x32\x33.org.sourceflow.gradient.entities.FrameStreamDetailH\x00\x42\t\n\x07payload*Z\n\x13MonitoringEventType\x12\t\n\x05\x46RAME\x10\x00\x12\x0b\n\x07RECEIVE\x10\x01\x12\n\n\x06RETURN\x10\x02\x12\n\n\x06\x45XCEPT\x10\x03\x12\x08\n\x04READ\x10\x04\x12\t\n\x05WRITE\x10\x05\x42\x41\n+org.sourceflow.gradient.monitoring.entitiesB\x12MonitoringEntitiesb\x06proto3'
  ,
  dependencies=[org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2.DESCRIPTOR,])

_MONITORINGEVENTTYPE = _descriptor.EnumDescriptor(
  name='MonitoringEventType',
  full_name='org.sourceflow.gradient.entities.MonitoringEventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FRAME', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RECEIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RETURN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXCEPT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='READ', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WRITE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1120,
  serialized_end=1210,
)
_sym_db.RegisterEnumDescriptor(_MONITORINGEVENTTYPE)

MonitoringEventType = enum_type_wrapper.EnumTypeWrapper(_MONITORINGEVENTTYPE)
FRAME = 0
RECEIVE = 1
RETURN = 2
EXCEPT = 3
READ = 4
WRITE = 5



_MONITORINGEVENT = _descriptor.Descriptor(
  name='MonitoringEvent',
  full_name='org.sourceflow.gradient.entities.MonitoringEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='org.sourceflow.gradient.entities.MonitoringEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frameId', full_name='org.sourceflow.gradient.entities.MonitoringEvent.frameId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='org.sourceflow.gradient.entities.MonitoringEvent.source', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='org.sourceflow.gradient.entities.MonitoringEvent.target', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datum', full_name='org.sourceflow.gradient.entities.MonitoringEvent.datum', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=326,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='org.sourceflow.gradient.entities.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.sourceflow.gradient.entities.Frame.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_code_element_id', full_name='org.sourceflow.gradient.entities.Frame.frame_code_element_id', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='org.sourceflow.gradient.entities.Frame.events', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='related_child_events', full_name='org.sourceflow.gradient.entities.Frame.related_child_events', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=527,
)


_MONITORINGSTREAMDETAIL = _descriptor.Descriptor(
  name='MonitoringStreamDetail',
  full_name='org.sourceflow.gradient.entities.MonitoringStreamDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='control', full_name='org.sourceflow.gradient.entities.MonitoringStreamDetail.control', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='org.sourceflow.gradient.entities.MonitoringStreamDetail.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=687,
)


_FRAMESTREAMDETAIL = _descriptor.Descriptor(
  name='FrameStreamDetail',
  full_name='org.sourceflow.gradient.entities.FrameStreamDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='control', full_name='org.sourceflow.gradient.entities.FrameStreamDetail.control', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frames', full_name='org.sourceflow.gradient.entities.FrameStreamDetail.frames', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=832,
)


_MONITORINGMESSAGE = _descriptor.Descriptor(
  name='MonitoringMessage',
  full_name='org.sourceflow.gradient.entities.MonitoringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_context', full_name='org.sourceflow.gradient.entities.MonitoringMessage.project_context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='monitoring_stream_detail', full_name='org.sourceflow.gradient.entities.MonitoringMessage.monitoring_stream_detail', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_stream_detail', full_name='org.sourceflow.gradient.entities.MonitoringMessage.frame_stream_detail', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='org.sourceflow.gradient.entities.MonitoringMessage.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=835,
  serialized_end=1118,
)

_MONITORINGEVENT.fields_by_name['type'].enum_type = _MONITORINGEVENTTYPE
_MONITORINGEVENT.fields_by_name['datum'].message_type = org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2._DATUM
_FRAME.fields_by_name['events'].message_type = _MONITORINGEVENT
_FRAME.fields_by_name['related_child_events'].message_type = _MONITORINGEVENT
_MONITORINGSTREAMDETAIL.fields_by_name['control'].message_type = org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2._STREAMCONTROL
_MONITORINGSTREAMDETAIL.fields_by_name['events'].message_type = _MONITORINGEVENT
_FRAMESTREAMDETAIL.fields_by_name['control'].message_type = org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2._STREAMCONTROL
_FRAMESTREAMDETAIL.fields_by_name['frames'].message_type = _FRAME
_MONITORINGMESSAGE.fields_by_name['project_context'].message_type = org_dot_sourceflow_dot_gradient_dot_entities_dot_common__pb2._PROJECTCONTEXT
_MONITORINGMESSAGE.fields_by_name['monitoring_stream_detail'].message_type = _MONITORINGSTREAMDETAIL
_MONITORINGMESSAGE.fields_by_name['frame_stream_detail'].message_type = _FRAMESTREAMDETAIL
_MONITORINGMESSAGE.oneofs_by_name['payload'].fields.append(
  _MONITORINGMESSAGE.fields_by_name['monitoring_stream_detail'])
_MONITORINGMESSAGE.fields_by_name['monitoring_stream_detail'].containing_oneof = _MONITORINGMESSAGE.oneofs_by_name['payload']
_MONITORINGMESSAGE.oneofs_by_name['payload'].fields.append(
  _MONITORINGMESSAGE.fields_by_name['frame_stream_detail'])
_MONITORINGMESSAGE.fields_by_name['frame_stream_detail'].containing_oneof = _MONITORINGMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['MonitoringEvent'] = _MONITORINGEVENT
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['MonitoringStreamDetail'] = _MONITORINGSTREAMDETAIL
DESCRIPTOR.message_types_by_name['FrameStreamDetail'] = _FRAMESTREAMDETAIL
DESCRIPTOR.message_types_by_name['MonitoringMessage'] = _MONITORINGMESSAGE
DESCRIPTOR.enum_types_by_name['MonitoringEventType'] = _MONITORINGEVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonitoringEvent = _reflection.GeneratedProtocolMessageType('MonitoringEvent', (_message.Message,), {
  'DESCRIPTOR' : _MONITORINGEVENT,
  '__module__' : 'org.sourceflow.gradient.entities.monitoring_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.MonitoringEvent)
  })
_sym_db.RegisterMessage(MonitoringEvent)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'org.sourceflow.gradient.entities.monitoring_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.Frame)
  })
_sym_db.RegisterMessage(Frame)

MonitoringStreamDetail = _reflection.GeneratedProtocolMessageType('MonitoringStreamDetail', (_message.Message,), {
  'DESCRIPTOR' : _MONITORINGSTREAMDETAIL,
  '__module__' : 'org.sourceflow.gradient.entities.monitoring_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.MonitoringStreamDetail)
  })
_sym_db.RegisterMessage(MonitoringStreamDetail)

FrameStreamDetail = _reflection.GeneratedProtocolMessageType('FrameStreamDetail', (_message.Message,), {
  'DESCRIPTOR' : _FRAMESTREAMDETAIL,
  '__module__' : 'org.sourceflow.gradient.entities.monitoring_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.FrameStreamDetail)
  })
_sym_db.RegisterMessage(FrameStreamDetail)

MonitoringMessage = _reflection.GeneratedProtocolMessageType('MonitoringMessage', (_message.Message,), {
  'DESCRIPTOR' : _MONITORINGMESSAGE,
  '__module__' : 'org.sourceflow.gradient.entities.monitoring_pb2'
  # @@protoc_insertion_point(class_scope:org.sourceflow.gradient.entities.MonitoringMessage)
  })
_sym_db.RegisterMessage(MonitoringMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)