version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.7
    commands:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh -q
      - bash miniconda.sh -b -p $HOME/miniconda
      - source $HOME/miniconda/etc/profile.d/conda.sh
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a

  pre_build:
    commands:
      - cd gradient-service-api && conda run --live-stream inv install
      - cd gradient-service-model && conda run --live-stream inv install

  build:
    commands:
      - conda run --live-stream inv build

  post_build:
    commands:
      - conda run --live-stream inv test

reports:
  test-gradient-service-model:
    files:
      - "*.xml"
    base-directory: "build/pytest/reports"
    file-format: JUNITXML
cache:
  paths:
    - $HOME/.cache/pip/**/*
    - $HOME/miniconda/pkgs
