version: 0.2

phases:

  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.7
    commands:
      - pip install --user --upgrade pip
      - pip install --user invoke
      - inv install-conda

  pre_build:
    commands:
      - which conda
      - cd gradient-service-api && conda run --live-stream inv install
      - cd gradient-service-model && conda run --live-stream inv install

  build:
    commands:
      - conda run --live-stream inv build

  post_build:
    commands:
      - conda run --live-stream inv test

reports:
  test-gradient-service-model:
    files:
      - "*.xml"
    base-directory: "build/pytest/reports"
    file-format: JUNITXML
cache:
  paths:
    - $HOME/.cache/pip/**/*
    - $HOME/miniconda/pkgs
