version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt
      - python -m venv gradient-service-domain/environment
      - pushd gradient-service-domain && source environment/bin/activate && pip install -r requirements/requirements.txt && popd

  build:
    commands:
      - pushd gradient-service-domain && source environment/bin/activate && inv build && inv test && popd

  post_build:
    commands:
      - pushd gradient-service-domain && source environment/bin/activate && inv publish && popd

reports:
  test-gradient-service-domain:
    files:
      - "*.xml"
    base-directory: gradient-service-domain/build/pytest/reports
    file-format: JUNITXML

cache:
  paths:
    - /root/.cache/pip/**/*
    - /root/gradient-service-inference/.hypothesis
    - /root/gradient-service-inference/tests/.hypothesis
