version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    on-failure: ABORT
    commands:
      - pip install -r requirements.txt
      - inv install -p gradient-service-domain

  build:
    commands:
      - inv build -p gradient-service-domain

  post_build:
    commands:
      - inv publish -p gradient-service-domain

reports:
  test-gradient-service-domain:
    files:
      - "*.xml"
    base-directory: build/pytest/reports
    file-format: JUNITXML

cache:
  paths:
    - $HOME/.cache/pip/**/*
