version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements
      - >
        pwd && \
        cd gradient-service-domain && \
        python -m venv environment && \
        source environment\bin\activate && \
        pip install -r requirements/requirements.txt
  #      - >
  #        pwd && \
  #        cd gradient-service-model && \
  #        python -m venv environment && \
  #        source environment\bin\activate && \
  #        pip install -r requirements

  build:
    commands:
      - >
        pwd && \
        cd gradient-service-domain && \
        source environment\bin\activate && \
        inv build && \
        inv test
  #      - >
  #        pwd && \
  #        cd gradient-service-model && \
  #        source environment\bin\activate && \
  #        inv build && \
  #        inv test


  post_build:
    commands:
      - >
        pwd && \
        cd gradient-service-domain && \
        source environment\bin\activate && \
        inv publish
#      - >
#        pwd && \
#        cd gradient-service-model && \
#        source environment\bin\activate && \
#        inv publish

reports:
  test-gradient-service-domain:
    files:
      - "*.xml"
    base-directory: build/pytest/reports
    file-format: JUNITXML

cache:
  paths:
    - /root/.cache/pip/**/*
    - /root/gradient-service-inference/.hypothesis
