name: gradient-infrastructure
channels:
  - conda-forge
dependencies:
  - python=3.7
  - invoke=1.5.0
  - pip=21.2
  - attrs=21.2.0
  - boto3=1.18.26
  - grpcio-tools=1.33.2
  - twine=3.4.2 # dev
  - conda-build=3.21.4 # dev
  - pip:
      - aws-cdk.core==1.122.0
      - aws-cdk.aws-s3==1.122.0
      - aws-cdk.aws-codebuild==1.122.0
      - aws-cdk.aws-codepipeline==1.122.0